# Generated by Django 3.2.6 on 2021-08-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0002_remove_pairs_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pairs',
        ),
    ]
