version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    volumes:
      - ./lesstools/:/code/lesstools/
      - ./static/:/code/static/
  dramatiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    env_file:
      - .env
    command: poetry run python manage.py rundramatiq
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    env_file:
      - .env
    command: poetry run python manage.py run_scheduler
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
      RABBITMQ_DEFAULT_VHOST:
