# Generated by Django 3.2.3 on 2021-06-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=200)),
                ('last_processed_block', models.IntegerField(default=1)),
                ('needs_poa_middleware', models.BooleanField(default=False)),
                ('native_api_url', models.CharField(max_length=400)),
                ('token_api_url', models.CharField(max_length=400)),
            ],
        ),
    ]
