# Generated by Django 3.2.3 on 2021-06-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
        ('networks', '0002_rename_networks_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='native_decimals',
            field=models.IntegerField(default=18),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.network')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.usdrate')),
            ],
        ),
    ]
