# Generated by Django 3.2.6 on 2021-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_auto_20210629_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
