# Generated by Django 3.2.6 on 2021-08-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_alter_usdrate_currency'),
        ('networks', '0005_auto_20210823_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttoken',
            name='usd_rate',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='rates.usdrate'),
        ),
    ]
