# Generated by Django 3.2.6 on 2021-08-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0006_alter_paymenttoken_usd_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='native_token',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='NOT_NEEDED+', to='networks.paymenttoken'),
            preserve_default=False,
        ),
    ]
