# Generated by Django 3.2.6 on 2021-08-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_alter_usdrate_currency'),
        ('networks', '0007_alter_network_native_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttoken',
            name='currency',
            field=models.CharField(help_text='Currency name for CoinGecko rates', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenttoken',
            name='usd_rate',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='rates.usdrate'),
        ),
    ]
