# Generated by Django 3.2.6 on 2021-08-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0008_auto_20210823_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='allows_holding_for_paid_plans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='network',
            name='less_token_address',
            field=models.CharField(default="0x62786Eeacc9246b4018e0146cb7a3efeACD9459D", max_length=128),
            preserve_default=False,
        ),
    ]
