# Generated by Django 3.2.6 on 2021-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0009_auto_20210825_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='less_token_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.CheckConstraint(check=models.Q(('allows_holding_for_paid_plans', True), ('less_token_address__isnull', False)), name='if_allows_holding_less_token_address_not_null'),
        ),
    ]
