# Generated by Django 3.2.6 on 2021-08-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0010_auto_20210825_1509'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='network',
            name='if_allows_holding_less_token_address_not_null',
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('allows_holding_for_paid_plans', True), ('less_token_address__isnull', False)), ('allows_holding_for_paid_plans', False), _connector='OR'), name='if_allows_holding_less_token_address_not_null'),
        ),
    ]
