# Generated by Django 3.2.6 on 2021-08-31 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0011_auto_20210825_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='native_token',
            field=models.ForeignKey(help_text='Just for deriving USD rates for native payments. So wrapped version will suffice too', on_delete=django.db.models.deletion.RESTRICT, related_name='NOT_NEEDED+', to='networks.paymenttoken'),
        ),
    ]
