# Generated by Django 3.2.6 on 2021-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdrate',
            name='currency',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
