# Generated by Django 3.2.6 on 2021-08-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_adv_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='description',
            field=models.CharField(blank=True, help_text='Company description(not for position TOP)', max_length=128),
        ),
        migrations.AlterField(
            model_name='adv',
            name='hash',
            field=models.CharField(blank=True, help_text='Hash for ipfs', max_length=256),
        ),
        migrations.AlterField(
            model_name='adv',
            name='icon',
            field=models.ImageField(help_text='image(for TOP not less 1100px/87px, for MID not less width and height 72px, for BOT not less width 353px/105px', upload_to='img-%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='name',
            field=models.CharField(blank=True, help_text='Company name(not for position TOP)', max_length=32),
        ),
        migrations.AlterField(
            model_name='adv',
            name='position',
            field=models.CharField(choices=[('TOP', 'top'), ('MID', 'mid'), ('BOT', 'bot')], default='MID', help_text='max count for TOP=1, MID=3, BOT=3', max_length=3),
        ),
        migrations.AlterField(
            model_name='adv',
            name='sub_name',
            field=models.CharField(blank=True, help_text='Company tag(not for position TOP)', max_length=32),
        ),
    ]
