# Generated by Django 3.2.6 on 2021-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20210826_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='description',
            field=models.CharField(blank=True, help_text='Company description (only for middle position)', max_length=128),
        ),
        migrations.AlterField(
            model_name='adv',
            name='icon',
            field=models.ImageField(help_text='image (for top position not less than 1100px/87px,\nfor middle position not less than 72px/72px,\nfor bottom position not less than 353px/105px)', upload_to='img-%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='name',
            field=models.CharField(blank=True, help_text='Company name (only for middle position)', max_length=32),
        ),
        migrations.AlterField(
            model_name='adv',
            name='position',
            field=models.CharField(choices=[('TOP', 'top'), ('MID', 'middle'), ('BOT', 'bottom')], help_text='max count for top=1, middle=3, bottom=3', max_length=3),
        ),
        migrations.AlterField(
            model_name='adv',
            name='sub_name',
            field=models.CharField(blank=True, help_text='Company tag (only for middle position)', max_length=32),
        ),
    ]
