# Generated by Django 3.2.3 on 2021-06-26 09:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='favourite_pairs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planpayment',
            name='currency',
            field=models.CharField(default='USDC', max_length=10),
            preserve_default=False,
        ),
    ]
