# Generated by Django 3.2.3 on 2021-06-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210626_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='payment_address',
        ),
    ]
