# Generated by Django 3.2.3 on 2021-08-10 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_advuser_payment_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='favourite_pairs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
    ]
