# Generated by Django 3.2.6 on 2021-08-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210813_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Free', max_length=10),
        ),
        migrations.AlterField(
            model_name='planprice',
            name='price',
            field=models.PositiveSmallIntegerField(help_text='You should have only one price record, and should not delete it.It is Standard plan price.Premium is assumed to be 2x bigger'),
        ),
    ]
