# Generated by Django 3.2.6 on 2021-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210818_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpayment',
            name='currency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planprice',
            name='price',
            field=models.PositiveSmallIntegerField(help_text='You should have only one price record, and should not delete it.\nIt is Standard plan price. Premium is assumed to be 2x more expensive.'),
        ),
    ]
