# Generated by Django 3.2.6 on 2021-08-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210820_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planpayment',
            name='currency',
        ),
    ]
