# Generated by Django 3.2.6 on 2021-08-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0005_auto_20210823_1457'),
        ('accounts', '0009_remove_planpayment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpayment',
            name='token_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.paymenttoken'),
        ),
    ]
