# Generated by Django 3.2.6 on 2021-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_planpayment_token_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpayment',
            name='end_time',
            field=models.DateTimeField(help_text='If end time equals payment time - the payment was unsuccessful and user did not upgrade', null=True),
        ),
    ]
