# Generated by Django 3.2.6 on 2021-08-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_planpayment_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planprice',
            name='price',
        ),
        migrations.AddField(
            model_name='planprice',
            name='holding_amount_in_less',
            field=models.PositiveIntegerField(default=1000, help_text='You should have only one amount record for holding, and should not delete it.\nIt is holding amount for Standard plan. Premium is assumed to be 2x bigger.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planprice',
            name='monthly_price_in_usd',
            field=models.PositiveSmallIntegerField(default=100, help_text='You should have only one price record for payments, and should not delete it.\nIt is Standard plan price. Premium is assumed to be 2x more expensive.'),
            preserve_default=False,
        ),
    ]
