# Generated by Django 3.2.6 on 2021-08-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210827_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='plan',
            new_name='plan_by_payments',
        ),
        migrations.AddField(
            model_name='advuser',
            name='plan_by_holding',
            field=models.CharField(choices=[('Free', 'Free'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Free', max_length=10),
        ),
    ]
