# Generated by Django 3.2.3 on 2021-08-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_id', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('eth_address', models.CharField(max_length=50, null=True)),
                ('bsc_address', models.CharField(max_length=50, null=True)),
                ('polygon_address', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
