# Generated by Django 3.2.3 on 2021-08-11 15:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_token_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='chat_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AddField(
            model_name='token',
            name='circulating_supply',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='cmc_slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='fully_diluted_market_cap',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='holders_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='market_cap',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='price_in_usd',
            field=models.DecimalField(decimal_places=15, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='total_supply',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='twitter_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='website_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='cmc_id',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
