# Generated by Django 3.2.6 on 2021-08-16 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0005_auto_20210816_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('ETH', 'Eth Platform'), ('BSC', 'Bsc Platform'), ('POLYGON', 'Polygon Platform')], max_length=10)),
                ('likes', models.PositiveIntegerField(default=0, editable=False)),
                ('dislikes', models.PositiveIntegerField(default=0, editable=False)),
                ('token_being_reviewed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='analytics.token')),
            ],
            options={
                'unique_together': {('address', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='UserPairVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(-1, 'Dislike'), (1, 'Like')], editable=False)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='analytics.pair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
