# Generated by Django 3.2.6 on 2021-08-17 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0006_pair_userpairvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='likes',
        ),
        migrations.AlterField(
            model_name='userpairvote',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='votes', to='analytics.pair'),
        ),
        migrations.AlterField(
            model_name='userpairvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpairvote',
            name='vote',
            field=models.SmallIntegerField(choices=[(-1, 'Dislike'), (1, 'Like'), (0, 'Neutral')], default=0, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='userpairvote',
            unique_together={('user', 'pair')},
        ),
    ]
