# Generated by Django 3.2.6 on 2021-10-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20210817_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPairCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('count', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
