# Generated by Django 3.2.6 on 2021-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_newpaircount'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='avalanche_address',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='token',
            name='fantom_address',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='token',
            name='xdai_address',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='platform',
            field=models.CharField(choices=[('ETH', 'Eth Platform'), ('BSC', 'Bsc Platform'), ('POLYGON', 'Polygon Platform'), ('XDAY', 'Xday Platform'), ('FANTOM', 'Fantom Platform'), ('AVALANCHE', 'Avalanche Platform')], max_length=10),
        ),
    ]
