# Generated by Django 3.2.6 on 2021-11-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20211111_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpaircount',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
